[2024-11-04T17:57:08.363+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T17:57:08.394+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yandex_task_dag.sending_to_clickhouse manual__2024-11-04T16:20:37.059441+00:00 [queued]>
[2024-11-04T17:57:08.408+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yandex_task_dag.sending_to_clickhouse manual__2024-11-04T16:20:37.059441+00:00 [queued]>
[2024-11-04T17:57:08.410+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 8
[2024-11-04T17:57:08.431+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): sending_to_clickhouse> on 2024-11-04 16:20:37.059441+00:00
[2024-11-04T17:57:08.440+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1538) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T17:57:08.444+0000] {standard_task_runner.py:72} INFO - Started process 1540 to run task
[2024-11-04T17:57:08.445+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'yandex_task_dag', 'sending_to_clickhouse', 'manual__2024-11-04T16:20:37.059441+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpoucyt1m8']
[2024-11-04T17:57:08.447+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask sending_to_clickhouse
[2024-11-04T17:57:08.525+0000] {task_command.py:467} INFO - Running <TaskInstance: yandex_task_dag.sending_to_clickhouse manual__2024-11-04T16:20:37.059441+00:00 [running]> on host d759fd8a501c
[2024-11-04T17:57:08.732+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yandex_task_dag' AIRFLOW_CTX_TASK_ID='sending_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T16:20:37.059441+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T16:20:37.059441+00:00'
[2024-11-04T17:57:08.735+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T17:57:08.736+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T17:57:08.737+0000] {logging_mixin.py:190} INFO - Current task name:sending_to_clickhouse state:running start_date:2024-11-04 17:57:08.395341+00:00
[2024-11-04T17:57:08.738+0000] {logging_mixin.py:190} INFO - Dag name:yandex_task_dag and current dag run status:running
[2024-11-04T17:57:08.741+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T17:57:09.364+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 20, in send_data_to_ch
    client.command(
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 350, in command
    response = self._raw_request(payload, params, headers, method, fields=fields, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 461, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 384, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://host.docker.internal:8123 received ClickHouse error code 519
 Code: 519. DB::NetException: All attempts to get table structure failed. Log: 

Code: 279. DB::NetException: All connection tries failed. Log: 

Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))

. (ALL_CONNECTION_TRIES_FAILED) (version 22.1.3.7 (official build))

. (NO_REMOTE_SHARD_AVAILABLE) (version 22.1.3.7 (official build))

[2024-11-04T17:57:09.397+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-04T17:57:09.397+0000] {logging_mixin.py:190} INFO - Task start:2024-11-04 17:57:08.395341+00:00 end:2024-11-04 17:57:09.396502+00:00 duration:1.001161
[2024-11-04T17:57:09.398+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): sending_to_clickhouse> dag:<DAG: yandex_task_dag> dagrun:<DagRun yandex_task_dag @ 2024-11-04 16:20:37.059441+00:00: manual__2024-11-04T16:20:37.059441+00:00, state:running, queued_at: 2024-11-04 17:57:05.444399+00:00. externally triggered: True>
[2024-11-04T17:57:09.399+0000] {logging_mixin.py:190} INFO - Failure caused by HTTPDriver for http://host.docker.internal:8123 received ClickHouse error code 519
 Code: 519. DB::NetException: All attempts to get table structure failed. Log: 

Code: 279. DB::NetException: All connection tries failed. Log: 

Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))

. (ALL_CONNECTION_TRIES_FAILED) (version 22.1.3.7 (official build))

. (NO_REMOTE_SHARD_AVAILABLE) (version 22.1.3.7 (official build))
[2024-11-04T17:57:09.399+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=yandex_task_dag, task_id=sending_to_clickhouse, run_id=manual__2024-11-04T16:20:37.059441+00:00, execution_date=20241104T162037, start_date=20241104T175708, end_date=20241104T175709
[2024-11-04T17:57:09.418+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T17:57:09.419+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task sending_to_clickhouse (HTTPDriver for http://host.docker.internal:8123 received ClickHouse error code 519
 Code: 519. DB::NetException: All attempts to get table structure failed. Log: 

Code: 279. DB::NetException: All connection tries failed. Log: 

Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))

. (ALL_CONNECTION_TRIES_FAILED) (version 22.1.3.7 (official build))

. (NO_REMOTE_SHARD_AVAILABLE) (version 22.1.3.7 (official build))
; 1540)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 20, in send_data_to_ch
    client.command(
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 350, in command
    response = self._raw_request(payload, params, headers, method, fields=fields, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 461, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 384, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://host.docker.internal:8123 received ClickHouse error code 519
 Code: 519. DB::NetException: All attempts to get table structure failed. Log: 

Code: 279. DB::NetException: All connection tries failed. Log: 

Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))
Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (host.docker.internal:8123). (NETWORK_ERROR) (version 22.1.3.7 (official build))

. (ALL_CONNECTION_TRIES_FAILED) (version 22.1.3.7 (official build))

. (NO_REMOTE_SHARD_AVAILABLE) (version 22.1.3.7 (official build))

[2024-11-04T17:57:09.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-04T17:57:09.488+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T17:57:09.492+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
