[2024-11-04T18:53:09.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T18:53:09.583+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yandex_test_dag.view_creation manual__2024-11-04T18:51:51.561534+00:00 [queued]>
[2024-11-04T18:53:09.593+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yandex_test_dag.view_creation manual__2024-11-04T18:51:51.561534+00:00 [queued]>
[2024-11-04T18:53:09.594+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-04T18:53:09.611+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): view_creation> on 2024-11-04 18:51:51.561534+00:00
[2024-11-04T18:53:09.620+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T18:53:09.622+0000] {standard_task_runner.py:72} INFO - Started process 2248 to run task
[2024-11-04T18:53:09.623+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'yandex_test_dag', 'view_creation', 'manual__2024-11-04T18:51:51.561534+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu1t__he2']
[2024-11-04T18:53:09.624+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask view_creation
[2024-11-04T18:53:09.685+0000] {task_command.py:467} INFO - Running <TaskInstance: yandex_test_dag.view_creation manual__2024-11-04T18:51:51.561534+00:00 [running]> on host d759fd8a501c
[2024-11-04T18:53:09.771+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yandex_test_dag' AIRFLOW_CTX_TASK_ID='view_creation' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T18:51:51.561534+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T18:51:51.561534+00:00'
[2024-11-04T18:53:09.773+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T18:53:09.773+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T18:53:09.773+0000] {logging_mixin.py:190} INFO - Current task name:view_creation state:running start_date:2024-11-04 18:53:09.584279+00:00
[2024-11-04T18:53:09.774+0000] {logging_mixin.py:190} INFO - Dag name:yandex_test_dag and current dag run status:running
[2024-11-04T18:53:09.775+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T18:53:09.775+0000] {sql.py:266} INFO - Executing: DO $$
BEGIN
    IF EXISTS replenishments THEN
        REFRESH MATERIALIZED VIEW replenishments;
    ELSE
        CREATE MATERIALIZED VIEW replenishments AS
        WITH first_reg_users AS (
            SELECT * FROM (
                SELECT *, min(date_registration::DATE) OVER (PARTITION BY email) AS first_reg_date
                FROM users
            ) u
            WHERE first_reg_date > '2016-04-01'
        )
        SELECT w.email AS email, sum(price) AS price_sum
        FROM first_reg_users f  -- get users who have first registration after webinar
        INNER JOIN webinar w ON f.email = w.email  -- intersecting with users from webinar
        INNER JOIN transactions t ON f.user_id = t.user_id  -- getting neccessary transactions
        GROUP BY w.email;  -- aggregate data for each participant
    END IF;
END
$$;
[2024-11-04T18:53:09.785+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2024-11-04T18:53:09.796+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2024-11-04T18:53:09.808+0000] {sql.py:509} INFO - Running statement: DO $$
BEGIN
    IF EXISTS replenishments THEN
        REFRESH MATERIALIZED VIEW replenishments;
    ELSE
        CREATE MATERIALIZED VIEW replenishments AS
        WITH first_reg_users AS (
            SELECT * FROM (
                SELECT *, min(date_registration::DATE) OVER (PARTITION BY email) AS first_reg_date
                FROM users
            ) u
            WHERE first_reg_date > '2016-04-01'
        )
        SELECT w.email AS email, sum(price) AS price_sum
        FROM first_reg_users f  -- get users who have first registration after webinar
        INNER JOIN webinar w ON f.email = w.email  -- intersecting with users from webinar
        INNER JOIN transactions t ON f.user_id = t.user_id  -- getting neccessary transactions
        GROUP BY w.email;  -- aggregate data for each participant
    END IF;
END
$$;, parameters: None
[2024-11-04T18:53:09.816+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "exists" does not exist
LINE 1: SELECT EXISTS replenishments
               ^
QUERY:  SELECT EXISTS replenishments
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF

[2024-11-04T18:53:09.832+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-04T18:53:09.833+0000] {logging_mixin.py:190} INFO - Task start:2024-11-04 18:53:09.584279+00:00 end:2024-11-04 18:53:09.831570+00:00 duration:0.247291
[2024-11-04T18:53:09.834+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): view_creation> dag:<DAG: yandex_test_dag> dagrun:<DagRun yandex_test_dag @ 2024-11-04 18:51:51.561534+00:00: manual__2024-11-04T18:51:51.561534+00:00, state:running, queued_at: 2024-11-04 18:53:07.308704+00:00. externally triggered: True>
[2024-11-04T18:53:09.834+0000] {logging_mixin.py:190} INFO - Failure caused by column "exists" does not exist
LINE 1: SELECT EXISTS replenishments
               ^
QUERY:  SELECT EXISTS replenishments
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
[2024-11-04T18:53:09.835+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=yandex_test_dag, task_id=view_creation, run_id=manual__2024-11-04T18:51:51.561534+00:00, execution_date=20241104T185151, start_date=20241104T185309, end_date=20241104T185309
[2024-11-04T18:53:09.855+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T18:53:09.856+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task view_creation (column "exists" does not exist
LINE 1: SELECT EXISTS replenishments
               ^
QUERY:  SELECT EXISTS replenishments
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF
; 2248)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "exists" does not exist
LINE 1: SELECT EXISTS replenishments
               ^
QUERY:  SELECT EXISTS replenishments
CONTEXT:  PL/pgSQL function inline_code_block line 3 at IF

[2024-11-04T18:53:09.879+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-04T18:53:09.891+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-04T18:53:09.906+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T18:53:09.912+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
